function create(__helpers) {
  var str = __helpers.s,
      empty = __helpers.e,
      notEmpty = __helpers.ne;

  return function render(data, out) {
    out.w('<div class="radial-box-light"><h2>About</h2><div class="glass-box p-32 t-l"><p>My name is Rich. I was raised in Tucson with 6 siblings by awesome parents and\nlove Arizona. My family life was simple but I guess having a mom and 4 sisters\nmade me appreciate how much they liked beauty and creative, artistic things in\nlife. Being married I bought alot of jewelry for gifts over the years. Now that\nI am retired I want to create my own objects of appreciation and share them\nwith\nothers.</p><p>This is an individually owned local business started in Tucson Arizona. My\nintention is to keep pricing competitive and give back to the community.\nPurchases over 100.00 USD will result in a 10.00 donation to the GIFT\nfoundation in Tucson. Purchases over 150.00 USD will result in a 10.00 donation\nto the GIFT foundation in Tucson and free shipping (in honor of my son Ryan who\nloves free\nshipping).</p><p>At Finite Designer Jewelry it is my personal desire to create objects for\nappreciation and enjoyment by those wearing them and those viewing them in\nmotion. Part of that enjoyment is kinetic in nature due to the fact that many\nhave moving parts. My philosophy is that jewelry is part fashion and part art.\nArt should not just hang on a wall but should be felt and noticed both by\nwearers and observers. It should impact a wide range of people. It should have\na positive impact in\ngeneral.</p><p>My mission is to create limited pieces of valuable items of combinations of\nsilver, gold, and semiprecious\nstone.</p><p>I am open to all forms of suggestions and or collaboration with my clients. I\nhope that by delivering high quality customer service I will build a reputation\nof forging long term repeat relationships built on trust and exceeding\nexpectations.</p></div></div>');
  };
}
(module.exports = require("marko").c(__filename)).c(create);